pipeline {
    agent any
    options {
        timestamps()
    }
    stages {
        stage ("Clone Git") {
            steps {
                git branch: 'main', url: 'https://github.com/nisharathod231/Kalopsia.git'
            }
        }
        stage ("Compile via NPM") {
            steps {
                dir('FrontEnd') {
                    sh 'npm install'
                }
            }
        }
    }
}