version: '3'
services:
  react-app:
    image: nishthapaul/kalopsia-frontend
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-app
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
      MYSQL_DATABASE: kalopsia
    volumes:
      - v-kalopsia-db:/var/lib/mysql

  spring-boot-app:
    restart: always
    image: nishthapaul/kalopsia-backend
    ports:
      - "9010:9010"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kalopsia?createIfNotExists=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
volumes:
  v-kalopsia-db: