pipeline {
    agent any
    options {
        timestamps()
    }
    environment {
        SCANNER_HOME=tool 'sonar-scanner'
    }
    stages {
        stage ("Clone Git") {
            steps {
                git branch: 'main', url: 'https://github.com/nisharathod231/Kalopsia.git'
            }
        }
        stage ("Compile via Maven") {
            steps {
                dir('Backend') {
                    sh 'mvn clean compile'
                }
            }
        }
        stage ("Unit Tests via Maven") {
            steps {
                dir('Backend') {
                    sh 'mvn test'
                }
            }
        }
        stage ("Check Code Coverage") {
            steps {
                dir('Backend') {
                    sh 'mvn verify'
                }
            }
        }
        stage ("Print inside backend") {
            steps {
                dir('Backend') {
                    sh 'pwd'
                    sh 'ls'
                }
            }
        }
        stage ("Print inside backend target") {
            steps {
                dir('Backend/target') {
                    sh 'pwd'
                    sh 'ls'
                }
            }
        }
        stage ("SonarQube Analysis") {
            steps {
                dir('Backend') {
                    sh ''' mvn sonar:sonar -Dsonar.url=http://localhost:9000/ -Dsonar.login=squ_220b6a20bb8c0a32af234c6af40ad105fa58ebdf \
                    -Dsonar.projectName=KalopsiaBackend \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=KalopsiaBackend '''
                }
            }
        }
        stage ("Build via Maven") {
            steps {
                dir('Backend') {
                    sh 'mvn install'
                }
            }
        }
    }
}
