pipeline {
    agent any
    options {
        timestamps()
    }
    stages {
        stage ("Clone Git") {
            steps {
                git branch: 'main', url: 'https://github.com/nisharathod231/Kalopsia.git'
            }
        }
        stage ("Build via Maven") {
            steps {
                dir('Backend') {
                    sh 'mvn clean install'
                }
            }
        }
    }
}
